// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetGift(ctx context.Context, id uuid.UUID) (Gift, error)
	InsertGift(ctx context.Context, arg InsertGiftParams) (Gift, error)
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
