// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/gifts": {
            "post": {
                "description": "Create a new gift",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gifts"
                ],
                "summary": "Create a new gift",
                "parameters": [
                    {
                        "description": "the request body for gift creation",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecase.CreateGiftInput"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/v1/transactions": {
            "post": {
                "description": "Create a new payment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "gifts"
                ],
                "summary": "Create a new payment",
                "parameters": [
                    {
                        "description": "the request body for transaction creation",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecase.ProcessPaymentInput"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "usecase.CreateGiftInput": {
            "description": "CreateGiftInput represents the input for creating a gift",
            "type": "object",
            "properties": {
                "gifter": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "recipient": {
                    "type": "string"
                }
            }
        },
        "usecase.ProcessPaymentInput": {
            "description": "ProcessPaymentInput represents the input for creating a transaction",
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "giftId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "I-GIFT",
	Description:      "I-GIFT is a platform for you to give gifts to your friends and family",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
