definitions:
  usecase.CreateGiftInput:
    description: CreateGiftInput represents the input for creating a gift
    properties:
      gifter:
        type: string
      message:
        type: string
      recipient:
        type: string
    type: object
  usecase.CreateUserInput:
    properties:
      email:
        type: string
      fullName:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  usecase.GenerateTokenInput:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  usecase.ProcessPaymentInput:
    description: ProcessPaymentInput represents the input for creating a transaction
    properties:
      amount:
        type: number
      giftId:
        type: string
    type: object
info:
  contact: {}
  description: I-GIFT is a platform for you to give gifts to your friends and family
  termsOfService: http://swagger.io/terms/
  title: I-GIFT
  version: "1.0"
paths:
  /auth/token:
    post:
      consumes:
      - application/json
      description: Generate a new access token
      parameters:
      - description: the request body for token generation
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/usecase.GenerateTokenInput'
      produces:
      - application/json
      responses: {}
      summary: Generate a new access token
      tags:
      - token
  /v1/files/upload:
    post:
      consumes:
      - multipart/form-data
      description: File upload
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses: {}
      summary: File upload
      tags:
      - files
  /v1/gifts:
    post:
      consumes:
      - application/json
      description: Create a new gift
      parameters:
      - description: the request body for gift creation
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/usecase.CreateGiftInput'
      produces:
      - application/json
      responses: {}
      summary: Create a new gift
      tags:
      - gifts
  /v1/transactions:
    post:
      consumes:
      - application/json
      description: Create a new payment
      parameters:
      - description: the request body for transaction creation
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/usecase.ProcessPaymentInput'
      produces:
      - application/json
      responses: {}
      summary: Create a new payment
      tags:
      - transactions
  /v1/users:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: the request body for user creation
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/usecase.CreateUserInput'
      produces:
      - application/json
      responses: {}
      summary: Create a new user
      tags:
      - users
swagger: "2.0"
